const products = [
  {
    _id: '1',
    name: 'Leather combat boots',
    image: '/images/combat-boots.jpg',
    description:
      'A pair of leather heavy duty no nonsense boots you will wear until you drop dead',
    brand: 'Duffy',
    category: 'Boots',
    price: 189.99,
    countInStock: 14,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '2',
    name: 'Doc Martens boots',
    image: '/images/doc-martens.jpg',
    description:
      'The latest worth the hype boots by Doc Martens, sure it will take you forever to break them in but after they are all yours, molded to the shape of your foot',
    brand: 'Doc Martens',
    category: 'Boots',
    price: 299.99,
    countInStock: 10,
    rating: 4.2,
    numReviews: 4,
  },
  {
    _id: '3',
    name: 'Nike Sneakers',
    image: '/images/sneakers-nike.jpg',
    description: 'Versatile, sturdy and comfy, what more can you ask for?',
    brand: 'Nike',
    category: 'Sneakers',
    price: 129.99,
    countInStock: 15,
    rating: 3.7,
    numReviews: 3,
  },
  {
    _id: '4',
    name: 'Diesel Sneakers',
    image: '/images/sneakers.jpg',
    description: 'Flashy and always ready to make an impression.',
    brand: 'Diesel',
    category: 'Sneakers',
    price: 299.99,
    countInStock: 12,
    rating: 5,
    numReviews: 3,
  },
  {
    _id: '5',
    name: 'Retro black stilettos',
    image: '/images/stiletto.jpg',
    description: 'Perfect for that special date night',
    brand: 'Pleaser',
    category: 'Heels',
    price: 79.99,
    countInStock: 17,
    rating: 3.5,
    numReviews: 2,
  },
  {
    _id: '6',
    name: 'Yellow pumps',
    image: '/images/yellow-pumps.jpg',
    description: 'Feminine trendy yet comfortable.',
    brand: 'Asos',
    category: 'Heels',
    price: 49.99,
    countInStock: 0,
    rating: 4,
    numReviews: 4,
  },
];

export default products;
